### ISSUE TITLE
TLS Support on esp8266

### ISSUE THREAD

**Issue by AndreaKrajewska** [InitialState/node-hub#5]
https://github.com/InitialState/node-hub/wiki/Part-2.-Example.-ESP8266

I believe this is incorrect at this point as I can connect using TLS to adafruit.io via TLS and they provide example code and links here. 
https://io.adafruit.com/blog/security/2016/07/05/adafruit-io-security-esp8266/

Would someone be up for creating a tutorial & example code to connect to initialstate? 
Thanks

**Comment by RChloe** [comment]
That's fantastic that they've added TLS support!

You should be able to easily modify the code here to support this update: https://github.com/initialstate/arduino_streamers/blob/master/arduinoESP8266wifishieldstream.ino

The main change would be switching line 12's **ISDestURL** from "insecure-groker.initialstate.com" to "groker.initialstate.com"
